### ISSUE TITLE
Feature Request: Multiple user exception

### ISSUE THREAD

**Issue by Lockszmith** [Villhellm/custom-sidebar#10]
First of all - Fantastic work on this one, really awesome!

I don't think it's currently possible, so suggesting a new feature.

Make the user/not_user directive accept multiple users.
If you don't want to break existing setups, add a users/not_users one that will work with lists instead of single entries.

**Comment by Villhellm** [comment]
Added in the latest release. It can either be a standard yaml list 
ie
```yaml
user:
  - paul
  - jeff
```

or just a comma separated list ie `user: paul, jeff`

let me know if you run into issues with it

**Comment by Lockszmith** [comment]
This looks great, I'll pull the beta and try it out

**Comment by Lockszmith** [comment]
"[I love it when a plan comes together](https://youtu.be/NsUFBm1uENs)"

Works perfectly, thank you so much.
