### ISSUE TITLE
New items don't display their text in a tooltip when the sidebar is collapsed

### ISSUE THREAD

**Issue by rccoleman** [Villhellm/custom-sidebar#12]
I'm just starting to play with this and it's working great for moving sidebar icons around and hiding ones that I don't want.  I also love that I can add new items to the sidebar, but the name of the new time doesn't appear to display in a tooltip like I see for the default items when the sidebar is collapsed.

Examples:

Existing item with tooltip:
![image](https://user-images.githubusercontent.com/860888/89338508-8927bf80-d651-11ea-8607-44c3c8c4f7c6.png)

New item with no tooltip:
![image](https://user-images.githubusercontent.com/860888/89338642-b2e0e680-d651-11ea-8c36-fcc25683d87d.png)

Expanded, showing the "Server Controls" text for the new item:
![image](https://user-images.githubusercontent.com/860888/89338844-08b58e80-d652-11ea-828d-6e422fc3706e.png)

Setting the name does change the text when the sidebar is open, but I just get no tooltip/popup when it's collapsed.

**Comment by Villhellm** [comment]
Yeah it turns out the tooltips are handled by TS event handlers that I don't have direct access to. It looks like in order to get tooltips working I would have to recreate them manually for the new items. Not impossible, but it will be a while before I get around to it

**Comment by rccoleman** [comment]
Thanks for the quick response.  I thought it might just be something like adding alt-text, but I couldn't find anything meaningful in the inspector and figured that it was probably more complicated.
