### ISSUE TITLE
0.115 Custom Items

### ISSUE THREAD

**Issue by acordill** [Villhellm/custom-sidebar#17]
Custom items become unusable in 0.115.0b1 with the following error in debug:
`7/hacsfiles/custom-sidebar/custom-sidebar.js:154 Uncaught TypeError: Cannot read property 'querySelector' of null
    at getSidebar (/hacsfiles/custom-sidebar/custom-sidebar.js:154)
    at run (/hacsfiles/custom-sidebar/custom-sidebar.js:127)`
My config:
`ns:
  - device: windows
    base_order: false
    order:
      - new_item: true
        item: Desktop Home
        href: /lovelace-yaml/home
        icon: "mdi:home-circle"
      - item: mobile home
        exact: true
        hide: true
      - item: map
        hide: false
      - item: developer tools
        hide: false
      - new_item: true
        item: Server Controls
        href: /config/server_control
        icon: "mdi:server"
        bottom: false
  - device: android
    base_order: false
    order:
      - item: desktop home
        exact: true
        hide: true
      - new_item: true
        item: Mobile Home
        href: /lovelace-yaml/mobile
        icon: "mdi:home-circle"
      - item: map
        hide: false
      - new_item: true
        item: Server Controls
        href: /config/server_control
        icon: "mdi:server"
        bottom: false`

**Comment by Villhellm** [comment]
Yup, looks like they killed that workaround with the new method of rearranging the sidebar. I'm not sure how much longer I'll be maintaining this plugin seeing as they are slowly making it obsolete

**Comment by Villhellm** [comment]
It looks like this is actually no longer an issue in the 115 beta 11. Let me know if it comes up again
