### ISSUE TITLE
Release v0.2.0, error's in log.

### ISSUE THREAD

**Issue by Jurgenn22** [Villhellm/custom-sidebar#18]
Hello,
Since this update, I have the error below in the log.

Greetings, Jurgen

<img width="1168" alt="Schermafbeelding 2020-09-09 om 14 35 45" src="https://user-images.githubusercontent.com/50082445/92599137-180ba580-f2aa-11ea-90cb-faa4aeba84eb.png">

**Comment by Villhellm** [comment]
The newest release should get rid of the error
