### ISSUE TITLE
Enable order dynamically

### ISSUE THREAD

**Issue by jdonzallaz** [Villhellm/custom-sidebar#24]
Hi,

Would it be possible to add an option to enable an order dynamically (or maybe there is already a way ?).
I would like to enable a custom order according to the state of an input_boolean.

My use-case is the following: Usually the order configuration will disable most sidebar items, leaving only things like dashboard, logbook and history. When I switch an input_boolean (like "dev mode") in the dashboard, it would use another order which shows most items.

Let me know if it's not clear.
Thank you !

**Comment by Villhellm** [comment]
Sorry, I don't have any interest in adding this feature. That would require tying the plugin to objects that may not exist if lovelace isn't loaded first.

 I recommend either a separate instance for development or just a separate dev user.
