### ISSUE TITLE
Reordering visible if the sidebar is open on page load

### ISSUE THREAD

**Issue by lokanx** [Villhellm/custom-sidebar#4]
Hi!

Awesome plugin, been looking for something like this. 👍 
It all works like a charm, but if you have the sidebar open on page load you could see reordering happen. Is it possible to hide menubar on load and display it after all dom elements have shifted order? I know it is just a beauty error/bug but   ##anyway

**Comment by Villhellm** [comment]
It wouldn't be possible to do this because the plugin doesn't get loaded until after the sidebar is already rendered.
