### ISSUE TITLE
Admin Exception

### ISSUE THREAD

**Issue by DuckyCrayfish** [Villhellm/custom-sidebar#43]
Could you add an exception for admins, so that administrator items can be customized independently?

My default customizations hide some sidebar items, but I would like to make an exception to show all sidebar items for administrators.

Thanks!

**Comment by n00bcodr** [comment]
This is not being maintained anymore, the developer has passed away.

See this for alternate version: https://github.com/Villhellm/custom-sidebar/issues/40#issuecomment-968252152

**Comment by DuckyCrayfish** [comment]
My apologies.
