### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by GitHubxtsnl** [Villhellm/custom-sidebar#5]
Just installed this frontend plugin and I'm getting the following error in my log.

HA version: 0.110.3 / HassOS 3.13
Custom Sidebar version: v0.1.2
Running Pi4

```
Log Details (ERROR)
Logger: frontend.js.latest.202005195
Source: components/system_log/__init__.py:209
First occurred: 1:55:56 PM (1 occurrences)
Last logged: 1:55:56 PM

https://<my_HA_server>/hacsfiles/custom-sidebar/custom-sidebar.js:62:22 Uncaught TypeError: Cannot read property 'length' of null
```

**Comment by Villhellm** [comment]
Please post your sidebar-order.yaml configuration

**Comment by GitHubxtsnl** [comment]
I have not created a sidebar-order.yaml yet, can this be the issue?

**Comment by Villhellm** [comment]
Yes. That's why it's in the instructions https://github.com/Villhellm/custom-sidebar#step-3

**Comment by Villhellm** [comment]
It you still get that error after following the install/configuration instructions please let me know and I will reopen the issue.

**Comment by GitHubxtsnl** [comment]
problem has been solved, I created the  sidebar-order.yaml file and restarted HA. thank you
